#####################################
#      Automate your workflow       #
#   GitHub Universe Workshop 2020   #
#####################################

# This workflow will run CI on your codebase, label your PR, and comment on the result

name: Test Label and Comment

on:
  pull_request: # the workflow will trigger on every pull request event

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: ['3.9', '3.10'] # matrix for building and testing your code across multiple node versions

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v3
        with:
            python-version: ${{ matrix.python }}
      - name: Install test dependencies
        run: python -m pip install -U tox
      - name: Test
        run: python -m tox -e py

  label:
    runs-on: ubuntu-latest

    needs: build #this ensures that we only trigger the label job if ci is successful

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['release']
            })

  comment:
    runs-on: ubuntu-latest

    needs: [build, label]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Comment on the result
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `
              Great job **@${context.payload.sender.login}**! Your CI passed, and the PR has been automatically labelled.

              Once ready, we will merge this PR to trigger the next part of the automation :rocket:
              `
            })
